# Generated by Django 3.2.7 on 2021-09-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='expenses',
            field=models.ManyToManyField(to='finance.Expense'),
        ),
    ]
